from model.upscaler.PASR import PyramidAttentionSR
from model.upscaler.PEDSR import PyramidEDSR
from model.upscaler.R2SR import Res2NetSR
from model.upscaler.SESR import SqueezeExcitationSR
from model.upscaler.SRRN import SRResNet
from model.upscaler.VDSR import VDSR
from model.upscaler.EDSR import EDSR
from model.upscaler.DSSR import DSSR
from model.upscaler.VDSSR import VDSSR
from model.upscaler.WDSSR import WDSSR
